# Generated by Django 5.2.4 on 2025-08-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatbotKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("knowledge_text", models.TextField()),
            ],
            options={
                "verbose_name": "Chatbot Knowledge",
                "verbose_name_plural": "Chatbot Knowledge",
            },
        ),
    ]
