# Generated by Django 5.2.4 on 2025-08-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_account_branch_account_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="user",
        ),
    ]
