# Generated by Django 5.2.4 on 2025-08-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_remove_account_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="user",
        ),
        migrations.RemoveField(
            model_name="creditcard",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.RemoveField(
            model_name="quickstat",
            name="user",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usernotificationsettings",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usersecuritysettings",
            name="user",
        ),
    ]
