# Generated by Django 5.2.4 on 2025-08-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0006_remove_chatmessage_user_remove_creditcard_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
    ]
