# Generated by Django 5.2.4 on 2025-08-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_remove_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("Savings Account", "savings"),
                    ("Current Account", "current"),
                    ("Loan Account", "loan"),
                    ("Fixed Deposit Account", "fd"),
                ],
                max_length=50,
            ),
        ),
    ]
