# Generated by Django 5.2.4 on 2025-08-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0008_alter_account_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("Savings Account", "Savings Account"),
                    ("Current Account", "Current Account"),
                    ("Loan Account", "Loan Account"),
                    ("Fixed Deposit Account", "Fixed Deposit Account"),
                ],
                max_length=50,
            ),
        ),
    ]
