# Generated by Django 5.2.4 on 2025-08-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0009_alter_account_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="method",
            field=models.CharField(
                choices=[
                    ("UPI", "UPI"),
                    ("Card", "Card"),
                    ("Netbanking", "Netbanking"),
                    ("NEFT", "NEFT"),
                    ("RTGS", "RTGS"),
                ],
                max_length=20,
            ),
        ),
    ]
