# Generated by Django 5.2.4 on 2025-08-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0010_alter_transaction_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("shopping", "Shopping"),
                    ("travel", "Travel"),
                    ("bills", "Bills"),
                    ("income", "Income"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="method",
            field=models.CharField(
                choices=[
                    ("upi", "UPI"),
                    ("card", "Card"),
                    ("netbanking", "Netbanking"),
                    ("neft", "NEFT"),
                    ("rtgs", "RTGS"),
                ],
                max_length=20,
            ),
        ),
    ]
