# Generated by Django 5.2.4 on 2025-08-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0011_alter_transaction_category_alter_transaction_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Shopping", "Shopping"),
                    ("Travel", "Travel"),
                    ("Bills", "Bills"),
                    ("Income", "Income"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="method",
            field=models.CharField(
                choices=[
                    ("UPI", "UPI"),
                    ("Card", "Card"),
                    ("Netbanking", "Netbanking"),
                    ("NEFT", "NEFT"),
                    ("RTGS", "RTGS"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("Debit", "Debit"), ("Credit", "Credit")], max_length=10
            ),
        ),
    ]
