# Generated by Django 5.2.4 on 2025-08-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chatbot",
            "0012_alter_transaction_category_alter_transaction_method_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("debit", "debit"), ("credit", "credit")], max_length=10
            ),
        ),
    ]
