# Generated by Django 5.2.4 on 2025-08-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0013_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("order", models.IntegerField(unique=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
