# Generated by Django 5.2.4 on 2025-08-31 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0015_creditcard_user_creditcardsettings_debitcardsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditcard",
            name="user",
        ),
    ]
