# Generated by Django 5.2.4 on 2025-08-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0016_remove_creditcard_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotknowledge",
            name="title",
            field=models.TextField(default="default"),
            preserve_default=False,
        ),
    ]
