# Generated by Django 5.2.4 on 2025-08-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0017_chatbotknowledge_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotknowledge",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
